import { supabase } from './supabase.js'

const state={session:null,profile:null,branch:null,categories:[],products:[],selectedCategory:'',cart:new Map(),paymentMethod:'cash'}
const $=id=>document.getElementById(id)
const el={backBtn:$('backBtn'),logoutBtn:$('logoutBtn'),branchText:$('branchText'),userName:$('userName'),searchInput:$('searchInput'),refreshBtn:$('refreshBtn'),categoryTabs:$('categoryTabs'),loading:$('loading'),empty:$('empty'),productGrid:$('productGrid'),cartCount:$('cartCount'),clearCartBtn:$('clearCartBtn'),emptyCart:$('emptyCart'),cartItems:$('cartItems'),subtotalText:$('subtotalText'),discountInput:$('discountInput'),totalText:$('totalText'),checkoutBtn:$('checkoutBtn'),pageMessage:$('pageMessage'),paymentModal:$('paymentModal'),closePaymentBtn:$('closePaymentBtn'),cancelPaymentBtn:$('cancelPaymentBtn'),paymentTotalText:$('paymentTotalText'),cashSection:$('cashSection'),qrSection:$('qrSection'),receivedInput:$('receivedInput'),quickCash:$('quickCash'),changeText:$('changeText'),saleNote:$('saleNote'),paymentMessage:$('paymentMessage'),confirmPaymentBtn:$('confirmPaymentBtn'),successModal:$('successModal'),invoiceText:$('invoiceText'),successTotal:$('successTotal'),successChange:$('successChange'),newSaleBtn:$('newSaleBtn')}

const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')
const money=v=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',minimumFractionDigits:2}).format(Number(v||0))
const items=()=>[...state.cart.values()]
const subtotal=()=>items().reduce((s,i)=>s+Number(i.price)*i.quantity,0)
const discount=()=>Math.max(Number(el.discountInput.value||0),0)
const total=()=>Math.max(subtotal()-discount(),0)
function msg(target,text=''){target.textContent=text}

async function requireSession(){const {data:{session},error}=await supabase.auth.getSession();if(error)throw error;if(!session){location.replace('./index.html');return null}state.session=session;return session}
async function loadProfile(id){const {data,error}=await supabase.from('profiles').select('id,full_name,role,branch_id').eq('id',id).maybeSingle();if(error)throw error;if(!data?.branch_id)throw new Error('บัญชียังไม่ได้กำหนดสาขา');state.profile=data}
async function loadBranch(){const {data,error}=await supabase.from('branches').select('id,name').eq('id',state.profile.branch_id).maybeSingle();if(error)throw error;if(!data)throw new Error('ไม่พบสาขา');state.branch=data}
async function loadCatalog(){el.loading.classList.remove('hidden');el.empty.classList.add('hidden');el.productGrid.classList.add('hidden');const [c,p]=await Promise.all([supabase.from('categories').select('id,name,display_order').eq('branch_id',state.profile.branch_id).eq('is_active',true).order('display_order'),supabase.from('products').select('id,category_id,name,sku,barcode,price,cost,image_url,display_order').eq('branch_id',state.profile.branch_id).eq('is_active',true).order('display_order').order('name')]);el.loading.classList.add('hidden');if(c.error)throw c.error;if(p.error)throw p.error;state.categories=c.data||[];state.products=p.data||[];renderCategories();renderProducts()}
function renderUser(){el.userName.textContent=state.profile.full_name||state.session.user.email.split('@')[0];el.branchText.textContent=`สาขา: ${state.branch.name}`}
function renderCategories(){el.categoryTabs.innerHTML=`<button class="tab ${!state.selectedCategory?'active':''}" data-cat="">ทั้งหมด</button>`+state.categories.map(c=>`<button class="tab ${state.selectedCategory===c.id?'active':''}" data-cat="${esc(c.id)}">${esc(c.name)}</button>`).join('')}
function filtered(){const q=el.searchInput.value.trim().toLowerCase();return state.products.filter(p=>(!state.selectedCategory||p.category_id===state.selectedCategory)&&(!q||[p.name,p.sku,p.barcode].filter(Boolean).join(' ').toLowerCase().includes(q)))}
function renderProducts(){const list=filtered();if(!list.length){el.empty.classList.remove('hidden');el.productGrid.classList.add('hidden');return}el.empty.classList.add('hidden');el.productGrid.classList.remove('hidden');el.productGrid.innerHTML=list.map(p=>`<article class="product-card"><button data-add="${esc(p.id)}"><div class="product-image">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" onerror="this.parentElement.innerHTML='🍽️'">`:'🍽️'}</div><div class="product-info"><h3>${esc(p.name)}</h3><div><strong>${money(p.price)}</strong><span class="plus">＋</span></div></div></button></article>`).join('')}
function add(id){const p=state.products.find(x=>x.id===id);if(!p)return;const old=state.cart.get(id);old?old.quantity++:state.cart.set(id,{...p,quantity:1});renderCart()}
function qty(id,d){const i=state.cart.get(id);if(!i)return;i.quantity+=d;if(i.quantity<=0)state.cart.delete(id);renderCart()}
function renderCart(){const list=items(),count=list.reduce((s,i)=>s+i.quantity,0);el.cartCount.textContent=`${count} รายการ`;el.emptyCart.classList.toggle('hidden',!!list.length);el.cartItems.classList.toggle('hidden',!list.length);el.cartItems.innerHTML=list.map(i=>`<div class="cart-item"><div><strong>${esc(i.name)}</strong><small>${money(i.price)} × ${i.quantity}</small><div class="qty"><button data-act="dec" data-id="${i.id}">−</button><b>${i.quantity}</b><button data-act="inc" data-id="${i.id}">＋</button><button class="remove" data-act="remove" data-id="${i.id}">ลบ</button></div></div><strong>${money(Number(i.price)*i.quantity)}</strong></div>`).join('');el.subtotalText.textContent=money(subtotal());el.totalText.textContent=money(total());el.checkoutBtn.disabled=!list.length;msg(el.pageMessage,discount()>subtotal()?'ส่วนลดมากกว่ายอดสินค้า':'')}
function openPayment(){if(!items().length||discount()>subtotal())return;state.paymentMethod='cash';el.paymentModal.classList.remove('hidden');el.paymentTotalText.textContent=money(total());el.receivedInput.value='';el.saleNote.value='';document.querySelectorAll('.method').forEach(b=>b.classList.toggle('active',b.dataset.method==='cash'));el.cashSection.classList.remove('hidden');el.qrSection.classList.add('hidden');renderQuickCash();updateChange();msg(el.paymentMessage,'')}
function closePayment(){el.paymentModal.classList.add('hidden')}
function renderQuickCash(){const t=total(),vals=[t,Math.ceil(t/20)*20,Math.ceil(t/100)*100,500,1000].filter((v,i,a)=>v>=t&&a.indexOf(v)===i).slice(0,4);el.quickCash.innerHTML=vals.map(v=>`<button data-cash="${v}">${v.toLocaleString('th-TH')}</button>`).join('')}
function updateChange(){el.changeText.textContent=money(Math.max(Number(el.receivedInput.value||0)-total(),0))}
async function confirmPayment(){const received=state.paymentMethod==='cash'?Number(el.receivedInput.value||0):total();if(state.paymentMethod==='cash'&&received<total()){msg(el.paymentMessage,'จำนวนเงินที่รับมายังไม่ครบ');return}el.confirmPaymentBtn.disabled=true;el.confirmPaymentBtn.textContent='กำลังบันทึก...';try{const {data,error}=await supabase.rpc('create_pos_sale',{p_branch_id:state.profile.branch_id,p_discount:discount(),p_payment_method:state.paymentMethod,p_received_amount:received,p_note:el.saleNote.value.trim()||null,p_items:items().map(i=>({product_id:i.id,quantity:i.quantity}))});if(error)throw error;closePayment();el.invoiceText.textContent=data.invoice_no;el.successTotal.textContent=money(data.total);el.successChange.textContent=money(data.change_amount);el.successModal.classList.remove('hidden')}catch(e){console.error(e);msg(el.paymentMessage,e.message||'บันทึกการขายไม่สำเร็จ')}finally{el.confirmPaymentBtn.disabled=false;el.confirmPaymentBtn.textContent='ยืนยันการชำระเงิน'}}
function newSale(){state.cart.clear();el.discountInput.value='0';el.successModal.classList.add('hidden');renderCart()}
async function logout(){await supabase.auth.signOut();location.replace('./index.html')}
async function init(){try{const s=await requireSession();if(!s)return;await loadProfile(s.user.id);await loadBranch();renderUser();await loadCatalog();renderCart()}catch(e){console.error(e);el.loading.classList.add('hidden');el.empty.classList.remove('hidden');el.empty.textContent=e.message}}

el.backBtn.onclick=()=>location.href='./dashboard.html';el.logoutBtn.onclick=logout;el.searchInput.oninput=renderProducts;el.refreshBtn.onclick=loadCatalog;el.categoryTabs.onclick=e=>{const b=e.target.closest('[data-cat]');if(!b)return;state.selectedCategory=b.dataset.cat;renderCategories();renderProducts()};el.productGrid.onclick=e=>{const b=e.target.closest('[data-add]');if(b)add(b.dataset.add)};el.cartItems.onclick=e=>{const b=e.target.closest('[data-act]');if(!b)return;b.dataset.act==='inc'?qty(b.dataset.id,1):b.dataset.act==='dec'?qty(b.dataset.id,-1):state.cart.delete(b.dataset.id);renderCart()};el.discountInput.oninput=renderCart;el.clearCartBtn.onclick=()=>{if(confirm('ล้างตะกร้าหรือไม่?')){state.cart.clear();renderCart()}};el.checkoutBtn.onclick=openPayment;document.querySelectorAll('.method').forEach(b=>b.onclick=()=>{state.paymentMethod=b.dataset.method;document.querySelectorAll('.method').forEach(x=>x.classList.toggle('active',x===b));el.cashSection.classList.toggle('hidden',state.paymentMethod!=='cash');el.qrSection.classList.toggle('hidden',state.paymentMethod!=='qr')});el.receivedInput.oninput=updateChange;el.quickCash.onclick=e=>{const b=e.target.closest('[data-cash]');if(b){el.receivedInput.value=b.dataset.cash;updateChange()}};el.closePaymentBtn.onclick=closePayment;el.cancelPaymentBtn.onclick=closePayment;el.confirmPaymentBtn.onclick=confirmPayment;el.newSaleBtn.onclick=newSale;supabase.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||!session)location.replace('./index.html')});init()
